# Generated by Django 5.2 on 2025-07-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
