# Generated by Django 5.2 on 2025-07-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0004_news_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="view_count",
        ),
    ]
